version: '3'
services:
  wordpress:
    image: wordpress
    container_name: my-wordpress
    environment:
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: developer
      WORDPRESS_DB_NAME: wordpress
    links:
      - db:mysql
    ports:
      - 80:80
    volumes:
      - ./data/blog/html/:/var/www/html
    depends_on:
      - db
    restart: always
  db:
    image: mariadb
    container_name: www-mariadb
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: developer
    volumes:
      - ./data/blog/mysql/:/var/lib/mysql
    restart: always